name: osc_adj
#filepath: ./osc_adj_generated.sv
filepath: mgenero_build/final.sv
template: OscillatorTemplate

pin:
    vss:
        direction: input
        datatype: real
        value: 0

    vdd:
        direction: input
        datatype: real
        value: 1.8

    out:
        direction: output
        datatype: bit

    ctrl0:
        direction: input
        datatype: binary_analog

    ctrl1:
        direction: input
        datatype: binary_analog


# Mapping between template and user pins
template_pins:
    out: out

# Additional template-required information
extras:
    approx_frequency: 2e9

test_config_file: ncsim.yaml
